name: Build and pack

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: PXByte.TuyaNET.API
      OUTPUT_DIR: ./KryptoPX.TuyaNet.API/output
      TARGET_FOLDER: ./KryptoPX.TuyaNet.API/
      CONFIGURATION: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build ${{ env.OUTPUT_DIR }} -o ${{ env.OUTPUT_DIR }}

      - name: Pack
        run: dotnet pack ${{ env.OUTPUT_DIR }} -o ${{ env.OUTPUT_DIR }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.TUYA_API_NAME }}
          path: ${{ env.OUTPUT_DIR }}
