name: Build and pack

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: PXByte.TuyaNET.API
      TARGET_PROJECT: ./KryptoPX.TuyaNet.API/KryptoPX.TuyaNet.API.csproj
      CONFIGURATION: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Build
        run: dotnet build ${{ env.TARGET_PROJECT }}

      - name: Pack
        run: dotnet pack ${{ env.TARGET_PROJECT }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}
          path: ${{ env.OUTPUT_DIR }}
